name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate JaCoCo report
        run: ./gradlew test jacocoTestReport

      - name: SonarQube analysis
        run: ./gradlew sonarqube -Dsonar.projectKey=RahulDeeti_checkr -Dsonar.organization=rahuldeeti -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}



#      - name: Analyze with SonarCloud
#        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        with:
#          args: >
#            -Dsonar.projectKey=RahulDeeti_checkr
#            -Dsonar.organization=rahuldeeti
#            -Dsonar.sources=src/main/java   # Adjust this path based on your source files location
#            -Dsonar.tests=src/test/java     # Adjust this path based on your test files location
#            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml